In [1]:
# Program for 'WHILE Loop' for finite times
N=int(input("Print numbers up to: "))
print(f"Print numbers up to: {N}")
i=1
while i<=N:
    print("Okay, running the WHILE Loop for %d times!" %i)
    i+=1

Print numbers up to: 7
Okay, running the WHILE Loop for 1 times!
Okay, running the WHILE Loop for 2 times!
Okay, running the WHILE Loop for 3 times!
Okay, running the WHILE Loop for 4 times!
Okay, running the WHILE Loop for 5 times!
Okay, running the WHILE Loop for 6 times!
Okay, running the WHILE Loop for 7 times!


### 0.1.2 LOOP statement using FOR loop

In [2]:
# An example FOR statement with LIST
for item in [1, 5.5, 16, "Tiger", False]:
    print(item)
    print(type(item))

1
<class 'int'>
5.5
<class 'float'>
16
<class 'int'>
Tiger
<class 'str'>
False
<class 'bool'>


In [3]:
# 'Hello World' for FOR loop
first_word = str(input("Enter 1st word : "))
print(f"Enter 1st word : {first_word}")
second_word = str(input("Enter 2nd word : "))
print(f"Enter 2nd word : {second_word}")
for greetings in first_word+second_word:
    print(greetings)

Enter 1st word : hello
Enter 2nd word : world
h
e
l
l
o
w
o
r
l
d


In [4]:
# Wring a range of numbers using 'arange' in NUMPY library
import numpy as np
print(np.arange(11))
print(np.arange(0,11))
print(np.arange(0,11,2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [5]:
#Wrining range using 'FOR' Loop
num=int(input("Print numbers up to:"))
print(f"Print numbers up to:{num}")
for i in range(1,num+1):
    print (i)

Print numbers up to:15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [6]:
 # FOR loop with augmented operation
total = 0
for i in range(0, 10):
    total += i
print(total)
# Verifition
print(sum(range(0, 10)))

45
45


In [7]:
# To generate Multiplication Table using FOR loop
current_value=int(input("Enter a number:"))
print(f"Enter a number:{current_value}")
for num in range(1, 11):
    product = num * current_value
    print(current_value, "x", num, "=" , product)
print("Job over, exit FOR Loop!")

Enter a number:68
68 x 1 = 68
68 x 2 = 136
68 x 3 = 204
68 x 4 = 272
68 x 5 = 340
68 x 6 = 408
68 x 7 = 476
68 x 8 = 544
68 x 9 = 612
68 x 10 = 680
Job over, exit FOR Loop!


In [8]:
# Zipping of two or multiple lIST/TUPLE/SET
list1 = {"V", "I", "B", "G", "Y", "O", "R"}
list2 = {1, 2, 3, 4, 5, 6, 7}
list3 = {"I", "II", "III", "IV", "V", "VI", "VII"}
for i, j, k in zip(list1, list2, list3):
    print(i, j, k)


B 1 VI
I 2 III
R 3 I
Y 4 VII
G 5 IV
V 6 V
O 7 II


In [10]:
# Zipping of two multiple lIST/TUPLE/SET
list1 = {"V", "I", "B", "G", "Y", "O", "R"}
list2 = {1, 2, 3, 4, 5, 6, 7}
for i, j in zip(list1, list2):
    print(i, j)

B 1
I 2
R 3
Y 4
G 5
V 6
O 7


In [11]:
# Looping operation inside 'Print'
zoo = ["Tiger", "Crocodile", "Parrot"]
for life, animal in enumerate(zoo):
    print("#%d: %s" % (life + 1, animal))

#1: Tiger
#2: Crocodile
#3: Parrot


### 0.1.3 Statement with WHILE-IF, FOR-IF etc

In [12]:
# Program to 'BREAK' infinite WHILE-IF loop (Print upto N-1 numbers)
i = 1
while i <= 10:
    print(i)
    i+=1
    if (i==5):
        break

1
2
3
4


In [13]:
# Program 'Jumping statement' using 'CONTINUE' in WHILE-IF loop (note the␣↪missing values) (Print upto N+1 numbers)
i = 0
while i <= 10-1:
    i+=1
    if (i==3 or i==6 or i==9):
        continue
    print(i)

1
2
4
5
7
8
10


In [15]:
# Table with a break
num=int(input("Enter a number:")) # Input statement
print(f"Enter a number:{num}")
current_value=0
while current_value<=num:
    current_value += 1
    product = num * current_value
    print(num, "x", current_value, "=" , product)
    if (current_value == 5):
        print("Exit the table after the current value becomes:",current_value)
        break

Enter a number:6
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
Exit the table after the current value becomes: 5


In [16]:
# Finding terms divisible by 5
mylist = [5, 7, 10, 20, 33, 46, 55]
print("My list is:",mylist)
def func(mylist):
    for num in mylist:
        if (num % 5 == 0):
            print(num)
print("Terms divisible by 5 are:")
func(mylist)

My list is: [5, 7, 10, 20, 33, 46, 55]
Terms divisible by 5 are:
5
10
20
55


In [17]:
#Sum of the number in a list divisible by 3
rlst= list(range(1, 11))
print(rlst)
total = 0
for i in range(1, 11):
    if i % 3 == 0:
        total += i
print(total)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
18


In [19]:
from statistics import *
from math import sqrt
nums=list(range( 10))
def stdDev(nums , xbar) :
    sumDevSq = 0.0
    for num in nums:
        dev = xbar - num
    sumDevSq = sumDevSq + dev * dev
    return sqrt(sumDevSq/ (len(nums) -1) )