In [36]:
# WHILE Loop using MATH
import math 
i = 1  
while (i < 11): 
    u_i = math.log(i) 
    print (round(u_i,3))
    i+=1 

0.0
0.693
1.099
1.386
1.609
1.792
1.946
2.079
2.197
2.303


In [2]:
# Properties of Numpy ‘Array’ 
import numpy as np 
data_lst=[2,4,1,6,8,0,9,7,3] 
data_arr=np.array(data_lst) 
print ("A List:",data_lst) 
print ("Numpy Array:",data_arr)
print("Data Dim:",np.ndim(data_arr))
print("Data Shape:",np.shape(data_arr)) 
print ("Data Size:",np.size(data_arr)) 
print ("Data Type:",data_arr.dtype)
print ("Data Byte:",data_arr.nbytes) 

A List: [2, 4, 1, 6, 8, 0, 9, 7, 3]
Numpy Array: [2 4 1 6 8 0 9 7 3]
Data Dim: 1
Data Shape: (9,)
Data Size: 9
Data Type: int32
Data Byte: 36


In [4]:
#Splitting a Numpy ‘Array’ 
 
data_lst=[[2 ,4 ,1],[6 ,8 ,0],[9 ,7 ,31]] 

In [5]:
#Ravel(Flatten) two or multi-dimensional Numpy 'Array'
 
data_lst=[[2 ,4 ,1],[6 ,8 ,0],[9 ,7 ,31]] 
data_arr= np.array(data_lst) 
data_flatten= np.ravel(data_arr)
print (f'NUMPY Array:\n {data_arr}') 
print (f'Disentangled (Flattened) NUMPY Array:\n { data_flatten}') 

NUMPY Array:
 [[ 2  4  1]
 [ 6  8  0]
 [ 9  7 31]]
Disentangled (Flattened) NUMPY Array:
 [ 2  4  1  6  8  0  9  7 31]


In [6]:
#Concatenate two Numpy ‘Array’ 
data_arr1=np.array([[2,4,1,6],[8,0,9,7.3]]) 
data_arr2=np.array([[2,4,1,6],[8,0,9,7.3]]) 
con_ver=np.concatenate(((data_arr1,data_arr2)), 
axis=0)
con_hor=np.concatenate (((data_arr1,data_arr2)), 
axis=1) 
print ("Concatenate vertically:\n", con_ver)
print ("Concatenate horizontally:\n", con_hor) 

Concatenate vertically:
 [[2.  4.  1.  6. ]
 [8.  0.  9.  7.3]
 [2.  4.  1.  6. ]
 [8.  0.  9.  7.3]]
Concatenate horizontally:
 [[2.  4.  1.  6.  2.  4.  1.  6. ]
 [8.  0.  9.  7.3 8.  0.  9.  7.3]]


In [9]:
#Converting Integer to Floating Array by Append
 
data_int_arr=np.array([2,4,1,6,8,0,9,7,3]) 
data_flt_arr=np.append(data_int_arr,0.007) 
print ("Array before append:", data_int_arr) 
print ("Array after append:", np.around(data_flt_arr,2)) 

Array before append: [2 4 1 6 8 0 9 7 3]
Array after append: [2.   4.   1.   6.   8.   0.   9.   7.   3.   0.01]


In [10]:
#Numpy ‘Sum’ from List 
 
data_list=[2,4,1,6,8,0,9,7,3]
data_sum=np.sum(data_list) 
print("Summation of numbers:", data_sum)

Summation of numbers: 40


In [16]:
#Numpy ‘Array’ from List 
 
my_int_list=[2,4,1,6,8,0,9,7,3] 
my_int_list_sqrt=np.sqrt(my_int_list) 
print (my_int_list_sqrt)

[1.41421356 2.         1.         2.44948974 2.82842712 0.
 3.         2.64575131 1.73205081]


In [25]:
#Numpy ‘Array’ from List 
 
my_int_list=[2,4,1,6,8,0,9,7,3] 
my_int_array=np.array(my_int_list) # Note: No commas 
print (my_int_array) 
print(type(my_int_array))
my_int_array.dtype 

[2 4 1 6 8 0 9 7 3]
<class 'numpy.ndarray'>


dtype('int32')

In [27]:
#Numpy ‘Array’ from List 
 
my_int_list=[2,4,1,6,8,0,9,7]
my_int_array=np.array(my_int_list)
print (my_int_array.size) 
print (my_int_array.shape) 

8
(8,)


In [17]:
#Some characteristics and manipulation of Numpy ‘Array’ 
 
data_list=[[0,1,2]],[[3,4,5]],[[6,7,8]] 
data_array=np.array(data_list) 
print ("List:\n", data_list) 
print ("Array:\n", data_array) 
print ("Size of array:\n", data_array.size) 
print ("Shape of array:\n", data_array.shape) 
print("Flatten array:\n", data_array.ravel()) 

List:
 ([[0, 1, 2]], [[3, 4, 5]], [[6, 7, 8]])
Array:
 [[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]
Size of array:
 9
Shape of array:
 (3, 1, 3)
Flatten array:
 [0 1 2 3 4 5 6 7 8]


In [19]:
#Numpy ‘Array’ from ’Arrange’ (Range) 
 
my_int_array1 = np.arange (9) 
print(my_int_array1)
print(type(my_int_array1)) # Builtin Python package 
print(my_int_array1.dtype) # With Numpy package 
print (my_int_array1.ndim) 

[0 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
int32
1


In [28]:
#Permutation using NUMPY
 

# 6.1.2 Matrix and their manipulation in Numpy 

In [1]:
#From Array to Matrix 

data_lst= [[2,4,1],[6,8,0] ,[9,7,31]]
print ("Data List:",data_lst) 
data_arr= np.array(data_lst) 
print ("Numpy Array:", data_arr) 
data_mat=np.matrix(data_arr)
print ("Numpy Matrix:",data_mat) 

Data List: [[2, 4, 1], [6, 8, 0], [9, 7, 31]]
Numpy Array: [[ 2  4  1]
 [ 6  8  0]
 [ 9  7 31]]
Numpy Matrix: [[ 2  4  1]
 [ 6  8  0]
 [ 9  7 31]]


In [2]:
#Null Matrix 
 
mat_null_3dim=np.zeros ((3,3)) 
print (mat_null_3dim) 
print (type (mat_null_3dim)) 
print (mat_null_3dim.dtype) 
print (mat_null_3dim.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(3, 3)


In [3]:
#Unit Matrix 
 
iden_mat4=np.eye (4,4) 
print (iden_mat4)  
print (iden_mat4.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [5]:
#One Matrix

mat34=np.ones((3,4)) 
print(mat34)
print (mat34.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [6]:
#Diagonal Matrix
 
MD=np.diag(np.arange(0, 20, 4)) 
print ("Diagonal matrix:",MD) 

Diagonal matrix: [[ 0  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0 12  0]
 [ 0  0  0  0 16]]


In [8]:
#Diagonal off-set Matrix 

N = 4
matU = np.eye(N, k=1)
matL = np.eye(N, k=-1) + np.eye(N)
print("matU: ", matU)
print("matL: ", matL)

matU:  [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
matL:  [[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 1. 1.]]


In [11]:
#Random Matrix
mat_rand4=np.random.random((4,4)) 
print (mat_rand4) 

[[0.21285836 0.08615188 0.82066757 0.60638629]
 [0.65473866 0.75852192 0.80662435 0.62046972]
 [0.74299104 0.58659999 0.634699   0.88358589]
 [0.51555796 0.29048978 0.52993484 0.72177241]]


In [14]:
#Dimension of Array and Matrix 
A = np.arange(8) 
M = np.arange (9).reshape(3,3) 
print ("A=",A) 
print("M=",M) 
print ("Dimension of array A:",A.ndim) 
print ("Number of elements in the matrix:", np.size(M)) 
print (f'The matrix is a {np.ndim(M)}-dimensional matrix') 
print (f'The matrix is a {M.ndim}-dimensional matrix') 

A= [0 1 2 3 4 5 6 7]
M= [[0 1 2]
 [3 4 5]
 [6 7 8]]
Dimension of array A: 1
Number of elements in the matrix: 9
The matrix is a 2-dimensional matrix
The matrix is a 2-dimensional matrix


In [15]:
#Summing two arrays
arrayl = np.array([1,4,8]) 
array2 = np.array([2,5,8]) 
print ("Sum of elements of two arrays:", arrayl+array2) 

Sum of elements of two arrays: [ 3  9 16]


In [18]:
#Reshaping of dimension of Array
one_dim_arr = np.arange(1,17) 
print ("One dimensional array: ",one_dim_arr) 
four_dim_arr = np.reshape(one_dim_arr,(4, 4)) 
two_dim_arr = np.reshape(one_dim_arr,(2,8)) 
return_one_dim = four_dim_arr.reshape(-1)
print ("Four (4x4) dimensional array:",four_dim_arr)
print ("Two (2x8) dimensional array:",two_dim_arr) 
print ("Return to one dimensional array:",return_one_dim)


One dimensional array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Four (4x4) dimensional array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Two (2x8) dimensional array: [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Return to one dimensional array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [20]:
#Transpose, Trace, Inverse,Rank,Determinant,Hermiticity of a Matrix
A=np.array([[1,3,0],[0,9,11],[1,1,2]]) 
print ("A=",A) 
print ("Transpose of matrix A:",np.transpose(A))
print ("Trace of matrix A:",np.trace(A)) 
print ("Inverse of matrix A:",np.linalg.inv(A)) 
print ("Rank of matrix A:",np.linalg.matrix_rank(A))
print ("Determinant of matrix A:",np.linalg.det(A)) 
print ("Hermitian of matrix A:",np.conj (A).T)

A= [[ 1  3  0]
 [ 0  9 11]
 [ 1  1  2]]
Transpose of matrix A: [[ 1  0  1]
 [ 3  9  1]
 [ 0 11  2]]
Trace of matrix A: 12
Inverse of matrix A: [[ 0.175 -0.15   0.825]
 [ 0.275  0.05  -0.275]
 [-0.225  0.05   0.225]]
Rank of matrix A: 3
Determinant of matrix A: 40.000000000000014
Hermitian of matrix A: [[ 1  0  1]
 [ 3  9  1]
 [ 0 11  2]]


In [21]:
#Simple Arithmetic with Matrices 
A=np.array([[1,2,3],[4,5,6] ,[7,8,9]]) 
B=np.array ([[9,8,7],[6,5,4],[3,2,1]]) 
print ("Matrix A=",A) 
print ("Matrix B=",B) 
print ("A+B=",np.add(A,B)) 
print ("A-B=",np.subtract (A,B))
print ("A*B= ",np.matmul(A,B)) 
print ("A/B (Termwise division)=",np.divide(A,B)) 

Matrix A= [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B= [[9 8 7]
 [6 5 4]
 [3 2 1]]
A+B= [[10 10 10]
 [10 10 10]
 [10 10 10]]
A-B= [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
A*B=  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
A/B (Termwise division)= [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [22]:
#Dot(Inner), Tensor (Outer) and Kronecker (Outer) product of two vectors
V1=np.array ([1,2,3]) 
V2=np.array([9,8,7]) 
print ("Matrix V1=",V1) 
print ("Matrix V2=",V2) 
print ("Dot (Inner) product of V1 & V2:",np.dot(V1,V2)) 
print ("Cross product of V1 & V2:",np.cross (V1, V2)) 
print ("Tensor (Outer) product of V1 & V2:",np.tensordot(V1, V2, axes=0)) 
print ("Kronecker product of V1 & v2:",np.kron(V1,V2)) 

Matrix V1= [1 2 3]
Matrix V2= [9 8 7]
Dot (Inner) product of V1 & V2: 46
Cross product of V1 & V2: [-10  20 -10]
Tensor (Outer) product of V1 & V2: [[ 9  8  7]
 [18 16 14]
 [27 24 21]]
Kronecker product of V1 & v2: [ 9  8  7 18 16 14 27 24 21]


## 6.1.3 Use of Linear Algebra package in Numpy 

In [23]:
#Inverse of a matrix
M= np.arange(1,19,2).reshape(3,3) 
print ("M=",M) 
InvM=np.linalg.inv (M) 
evalues, evectors = np.linalg.eig(M) 
print ("Inverse of M:", InvM) 

M= [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
Inverse of M: [[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]


In [24]:
#Eigen values and Eigen vectors 
N=4
MN=np.eye (N,k=1) +np.eye (N,k=-1) 
print ("MN=",MN) 
evalMN, evecMN = np.linalg.eig(MN) 
print ("Eigen values:",evalMN) 
print ("Eigen vectors:",evecMN) 
print ("Normalized Eigen vectors:",np.around(evecMN ,2) /np.linalg.norm(evecMN)) 

MN= [[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]
Eigen values: [-1.61803399 -0.61803399  1.61803399  0.61803399]
Eigen vectors: [[ 0.37174803  0.60150096 -0.37174803 -0.60150096]
 [-0.60150096 -0.37174803 -0.60150096 -0.37174803]
 [ 0.60150096 -0.37174803 -0.60150096  0.37174803]
 [-0.37174803  0.60150096 -0.37174803  0.60150096]]
Normalized Eigen vectors: [[ 0.185  0.3   -0.185 -0.3  ]
 [-0.3   -0.185 -0.3   -0.185]
 [ 0.3   -0.185 -0.3    0.185]
 [-0.185  0.3   -0.185  0.3  ]]


In [25]:
#Eigen values and Eigen vectors
M= np.arange(1,19,2).reshape(3,3) 
print ("M=",M) 
np.linalg.inv(M) 
evalues, evectors = np.linalg.eig(M) 
print ("Eigen values:", evalues) 
print ("Eigen vectors:",evectors) 

M= [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
Eigen values: [ 2.94452187e+01 -2.44521872e+00 -1.61086274e-15]
Eigen vectors: [[ 0.20079137  0.79227344  0.40824829]
 [ 0.5165778   0.09475476 -0.81649658]
 [ 0.83236422 -0.60276391  0.40824829]]


In [26]:
#Diagonalization by Similarity Transformation 
M= np.arange(1,19,2).reshape(3,3) 
(d,P)=np.linalg.eig(M) 
D=np.diag(d) 
print ("M=",M) 
print ("Transformation matrix (p) is:",np.around (P,2)) 
print ("Diagonal matrix (D) is:",D) 
print ("Diagonal matrix is: (Verification)",d)

M= [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
Transformation matrix (p) is: [[ 0.2   0.79  0.41]
 [ 0.52  0.09 -0.82]
 [ 0.83 -0.6   0.41]]
Diagonal matrix (D) is: [[ 2.94452187e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.44521872e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.61086274e-15]]
Diagonal matrix is: (Verification) [ 2.94452187e+01 -2.44521872e+00 -1.61086274e-15]


In [27]:
#Singular-value decomposition 
from scipy.linalg import svd 
# define a matrix 
M = np.array([[4, 72], [3, 14], [8, 2]])
print ("M=",M) 
# SVD calculation 
U, s, VT = svd(M) 
print("Left transformation matrix ",U) 
print ("Right transformation matrix (VT):",VT) 
print ("Column matrix (s):",s) 

M= [[ 4 72]
 [ 3 14]
 [ 8  2]]
Left transformation matrix  [[ 0.98067142 -0.08381868  0.17679932]
 [ 0.19264847  0.25566091 -0.94737747]
 [ 0.03420725  0.96312612  0.26686689]]
Right transformation matrix (VT): [[ 0.0649307   0.99788978]
 [ 0.99788978 -0.0649307 ]]
Column matrix (s): [73.52899788  8.1539236 ]


In [30]:
#Solution of linear equation 
A = np.array([[1, 2.6, 3], [4, 5, 6], [7, .8,9]])
B=np.array([1.5,2.1,3.7]) 
X = np.linalg.solve(A, B) 
print("Values of the components of X vectors (x1,x2,x3) are:",X) 
np.allclose(np.dot (A, X), B) # Verification 

Values of the components of X vectors (x1,x2,x3) are: [-0.46515152 -0.15151515  0.78636364]


True

In [31]:
#Sparse matrix 
np.concatenate 
np.conj 
np.conjugate 
np.convolve 

<function convolve at 0x000002334718A930>

In [32]:
#Reading, saving data and writing using NUMPY 
np.save('data_saved.py',data_arr) 
np.loadtxt (data_arr) 

TypeError: non-string returned while reading data

In [ ]:
#Quit
quit()

In [3]:
!pip install nbmerge

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import nbmerge
!nbmerge loop-while.ipynb loop-decision-2.ipynb "Controlled operations.ipynb" > merged.ipynb

C:\Users\Prith\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbformat\__init__.py:93: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)
